<?php
/**
 * SearchBody
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Store API
 *
 * This endpoint reference contains an overview of all endpoints comprising the Shopware Store API
 *
 * OpenAPI spec version: 6.4.8.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * SearchBody Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SearchBody implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'search_body';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'order' => 'string',
'limit' => 'int',
'p' => 'int',
'manufacturer' => 'string',
'min_price' => 'int',
'max_price' => 'int',
'rating' => 'int',
'shipping_free' => 'bool',
'properties' => 'string',
'manufacturer_filter' => 'bool',
'price_filter' => 'bool',
'rating_filter' => 'bool',
'shipping_free_filter' => 'bool',
'property_filter' => 'bool',
'property_whitelist' => 'string',
'reduce_aggregations' => 'string',
'no_aggregations' => 'string',
'only_aggregations' => 'string'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'order' => null,
'limit' => null,
'p' => null,
'manufacturer' => null,
'min_price' => null,
'max_price' => null,
'rating' => null,
'shipping_free' => null,
'properties' => null,
'manufacturer_filter' => null,
'price_filter' => null,
'rating_filter' => null,
'shipping_free_filter' => null,
'property_filter' => null,
'property_whitelist' => null,
'reduce_aggregations' => null,
'no_aggregations' => null,
'only_aggregations' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'order' => 'order',
'limit' => 'limit',
'p' => 'p',
'manufacturer' => 'manufacturer',
'min_price' => 'min-price',
'max_price' => 'max-price',
'rating' => 'rating',
'shipping_free' => 'shipping-free',
'properties' => 'properties',
'manufacturer_filter' => 'manufacturer-filter',
'price_filter' => 'price-filter',
'rating_filter' => 'rating-filter',
'shipping_free_filter' => 'shipping-free-filter',
'property_filter' => 'property-filter',
'property_whitelist' => 'property-whitelist',
'reduce_aggregations' => 'reduce-aggregations',
'no_aggregations' => 'no-aggregations',
'only_aggregations' => 'only-aggregations'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'order' => 'setOrder',
'limit' => 'setLimit',
'p' => 'setP',
'manufacturer' => 'setManufacturer',
'min_price' => 'setMinPrice',
'max_price' => 'setMaxPrice',
'rating' => 'setRating',
'shipping_free' => 'setShippingFree',
'properties' => 'setProperties',
'manufacturer_filter' => 'setManufacturerFilter',
'price_filter' => 'setPriceFilter',
'rating_filter' => 'setRatingFilter',
'shipping_free_filter' => 'setShippingFreeFilter',
'property_filter' => 'setPropertyFilter',
'property_whitelist' => 'setPropertyWhitelist',
'reduce_aggregations' => 'setReduceAggregations',
'no_aggregations' => 'setNoAggregations',
'only_aggregations' => 'setOnlyAggregations'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'order' => 'getOrder',
'limit' => 'getLimit',
'p' => 'getP',
'manufacturer' => 'getManufacturer',
'min_price' => 'getMinPrice',
'max_price' => 'getMaxPrice',
'rating' => 'getRating',
'shipping_free' => 'getShippingFree',
'properties' => 'getProperties',
'manufacturer_filter' => 'getManufacturerFilter',
'price_filter' => 'getPriceFilter',
'rating_filter' => 'getRatingFilter',
'shipping_free_filter' => 'getShippingFreeFilter',
'property_filter' => 'getPropertyFilter',
'property_whitelist' => 'getPropertyWhitelist',
'reduce_aggregations' => 'getReduceAggregations',
'no_aggregations' => 'getNoAggregations',
'only_aggregations' => 'getOnlyAggregations'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['order'] = isset($data['order']) ? $data['order'] : null;
        $this->container['limit'] = isset($data['limit']) ? $data['limit'] : null;
        $this->container['p'] = isset($data['p']) ? $data['p'] : 1;
        $this->container['manufacturer'] = isset($data['manufacturer']) ? $data['manufacturer'] : null;
        $this->container['min_price'] = isset($data['min_price']) ? $data['min_price'] : 0;
        $this->container['max_price'] = isset($data['max_price']) ? $data['max_price'] : 0;
        $this->container['rating'] = isset($data['rating']) ? $data['rating'] : null;
        $this->container['shipping_free'] = isset($data['shipping_free']) ? $data['shipping_free'] : false;
        $this->container['properties'] = isset($data['properties']) ? $data['properties'] : null;
        $this->container['manufacturer_filter'] = isset($data['manufacturer_filter']) ? $data['manufacturer_filter'] : true;
        $this->container['price_filter'] = isset($data['price_filter']) ? $data['price_filter'] : true;
        $this->container['rating_filter'] = isset($data['rating_filter']) ? $data['rating_filter'] : true;
        $this->container['shipping_free_filter'] = isset($data['shipping_free_filter']) ? $data['shipping_free_filter'] : true;
        $this->container['property_filter'] = isset($data['property_filter']) ? $data['property_filter'] : true;
        $this->container['property_whitelist'] = isset($data['property_whitelist']) ? $data['property_whitelist'] : null;
        $this->container['reduce_aggregations'] = isset($data['reduce_aggregations']) ? $data['reduce_aggregations'] : null;
        $this->container['no_aggregations'] = isset($data['no_aggregations']) ? $data['no_aggregations'] : null;
        $this->container['only_aggregations'] = isset($data['only_aggregations']) ? $data['only_aggregations'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets order
     *
     * @return string
     */
    public function getOrder()
    {
        return $this->container['order'];
    }

    /**
     * Sets order
     *
     * @param string $order Specifies the sorting of the products by `availableSortings`. If not set, the default sorting will be set according to the shop settings. The available sorting options are sent within the response under the `availableSortings` key. In order to sort by a field, consider using the `sort` parameter from the listing criteria. Do not use both parameters together, as it might lead to unexpected results.
     *
     * @return $this
     */
    public function setOrder($order)
    {
        $this->container['order'] = $order;

        return $this;
    }

    /**
     * Gets limit
     *
     * @return int
     */
    public function getLimit()
    {
        return $this->container['limit'];
    }

    /**
     * Sets limit
     *
     * @param int $limit Number of items per result page. If not set, the limit will be set according to the default products per page, defined in the system settings.
     *
     * @return $this
     */
    public function setLimit($limit)
    {
        $this->container['limit'] = $limit;

        return $this;
    }

    /**
     * Gets p
     *
     * @return int
     */
    public function getP()
    {
        return $this->container['p'];
    }

    /**
     * Sets p
     *
     * @param int $p Search result page
     *
     * @return $this
     */
    public function setP($p)
    {
        $this->container['p'] = $p;

        return $this;
    }

    /**
     * Gets manufacturer
     *
     * @return string
     */
    public function getManufacturer()
    {
        return $this->container['manufacturer'];
    }

    /**
     * Sets manufacturer
     *
     * @param string $manufacturer Filter by manufacturers. List of manufacturer identifiers separated by a `|`.
     *
     * @return $this
     */
    public function setManufacturer($manufacturer)
    {
        $this->container['manufacturer'] = $manufacturer;

        return $this;
    }

    /**
     * Gets min_price
     *
     * @return int
     */
    public function getMinPrice()
    {
        return $this->container['min_price'];
    }

    /**
     * Sets min_price
     *
     * @param int $min_price Filters by a minimum product price. Has to be lower than the `max-price` filter.
     *
     * @return $this
     */
    public function setMinPrice($min_price)
    {
        $this->container['min_price'] = $min_price;

        return $this;
    }

    /**
     * Gets max_price
     *
     * @return int
     */
    public function getMaxPrice()
    {
        return $this->container['max_price'];
    }

    /**
     * Sets max_price
     *
     * @param int $max_price Filters by a maximum product price. Has to be higher than the `min-price` filter.
     *
     * @return $this
     */
    public function setMaxPrice($max_price)
    {
        $this->container['max_price'] = $max_price;

        return $this;
    }

    /**
     * Gets rating
     *
     * @return int
     */
    public function getRating()
    {
        return $this->container['rating'];
    }

    /**
     * Sets rating
     *
     * @param int $rating Filter products with a minimum average rating.
     *
     * @return $this
     */
    public function setRating($rating)
    {
        $this->container['rating'] = $rating;

        return $this;
    }

    /**
     * Gets shipping_free
     *
     * @return bool
     */
    public function getShippingFree()
    {
        return $this->container['shipping_free'];
    }

    /**
     * Sets shipping_free
     *
     * @param bool $shipping_free Filters products that are marked as shipping-free.
     *
     * @return $this
     */
    public function setShippingFree($shipping_free)
    {
        $this->container['shipping_free'] = $shipping_free;

        return $this;
    }

    /**
     * Gets properties
     *
     * @return string
     */
    public function getProperties()
    {
        return $this->container['properties'];
    }

    /**
     * Sets properties
     *
     * @param string $properties Filters products by their properties. List of property identifiers separated by a `|`.
     *
     * @return $this
     */
    public function setProperties($properties)
    {
        $this->container['properties'] = $properties;

        return $this;
    }

    /**
     * Gets manufacturer_filter
     *
     * @return bool
     */
    public function getManufacturerFilter()
    {
        return $this->container['manufacturer_filter'];
    }

    /**
     * Sets manufacturer_filter
     *
     * @param bool $manufacturer_filter Enables/disabled filtering by manufacturer. If set to false, the `manufacturer` filter will be ignored. Also the `aggregations[manufacturer]` key will be removed from the response.
     *
     * @return $this
     */
    public function setManufacturerFilter($manufacturer_filter)
    {
        $this->container['manufacturer_filter'] = $manufacturer_filter;

        return $this;
    }

    /**
     * Gets price_filter
     *
     * @return bool
     */
    public function getPriceFilter()
    {
        return $this->container['price_filter'];
    }

    /**
     * Sets price_filter
     *
     * @param bool $price_filter Enables/disabled filtering by price. If set to false, the `min-price` and `max-price` filter will be ignored. Also the `aggregations[price]` key will be removed from the response.
     *
     * @return $this
     */
    public function setPriceFilter($price_filter)
    {
        $this->container['price_filter'] = $price_filter;

        return $this;
    }

    /**
     * Gets rating_filter
     *
     * @return bool
     */
    public function getRatingFilter()
    {
        return $this->container['rating_filter'];
    }

    /**
     * Sets rating_filter
     *
     * @param bool $rating_filter Enables/disabled filtering by rating. If set to false, the `rating` filter will be ignored. Also the `aggregations[rating]` key will be removed from the response.
     *
     * @return $this
     */
    public function setRatingFilter($rating_filter)
    {
        $this->container['rating_filter'] = $rating_filter;

        return $this;
    }

    /**
     * Gets shipping_free_filter
     *
     * @return bool
     */
    public function getShippingFreeFilter()
    {
        return $this->container['shipping_free_filter'];
    }

    /**
     * Sets shipping_free_filter
     *
     * @param bool $shipping_free_filter Enables/disabled filtering by shipping-free products. If set to false, the `shipping-free` filter will be ignored. Also the `aggregations[shipping-free]` key will be removed from the response.
     *
     * @return $this
     */
    public function setShippingFreeFilter($shipping_free_filter)
    {
        $this->container['shipping_free_filter'] = $shipping_free_filter;

        return $this;
    }

    /**
     * Gets property_filter
     *
     * @return bool
     */
    public function getPropertyFilter()
    {
        return $this->container['property_filter'];
    }

    /**
     * Sets property_filter
     *
     * @param bool $property_filter Enables/disabled filtering by properties products. If set to false, the `properties` filter will be ignored. Also the `aggregations[properties]` key will be removed from the response.
     *
     * @return $this
     */
    public function setPropertyFilter($property_filter)
    {
        $this->container['property_filter'] = $property_filter;

        return $this;
    }

    /**
     * Gets property_whitelist
     *
     * @return string
     */
    public function getPropertyWhitelist()
    {
        return $this->container['property_whitelist'];
    }

    /**
     * Sets property_whitelist
     *
     * @param string $property_whitelist A whitelist of property identifiers which can be used for filtering. List of property identifiers separated by a `|`. The `property-filter` must be `true`, otherwise the whitelist has no effect.
     *
     * @return $this
     */
    public function setPropertyWhitelist($property_whitelist)
    {
        $this->container['property_whitelist'] = $property_whitelist;

        return $this;
    }

    /**
     * Gets reduce_aggregations
     *
     * @return string
     */
    public function getReduceAggregations()
    {
        return $this->container['reduce_aggregations'];
    }

    /**
     * Sets reduce_aggregations
     *
     * @param string $reduce_aggregations By sending the parameter `reduce-aggregations` , the post-filters that were applied by the customer, are also applied to the aggregations. This has the consequence that only values are returned in the aggregations that would lead to further filter results. This parameter is a flag, the value has no effect.
     *
     * @return $this
     */
    public function setReduceAggregations($reduce_aggregations)
    {
        $this->container['reduce_aggregations'] = $reduce_aggregations;

        return $this;
    }

    /**
     * Gets no_aggregations
     *
     * @return string
     */
    public function getNoAggregations()
    {
        return $this->container['no_aggregations'];
    }

    /**
     * Sets no_aggregations
     *
     * @param string $no_aggregations Resets all aggregations in the criteria. This parameter is a flag, the value has no effect.
     *
     * @return $this
     */
    public function setNoAggregations($no_aggregations)
    {
        $this->container['no_aggregations'] = $no_aggregations;

        return $this;
    }

    /**
     * Gets only_aggregations
     *
     * @return string
     */
    public function getOnlyAggregations()
    {
        return $this->container['only_aggregations'];
    }

    /**
     * Sets only_aggregations
     *
     * @param string $only_aggregations If this flag is set, no products are fetched. Sorting and associations are also ignored. This parameter is a flag, the value has no effect.
     *
     * @return $this
     */
    public function setOnlyAggregations($only_aggregations)
    {
        $this->container['only_aggregations'] = $only_aggregations;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
