<?php
/**
 * AccountRegisterBodyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Store API
 *
 * This endpoint reference contains an overview of all endpoints comprising the Shopware Store API
 *
 * OpenAPI spec version: 6.4.8.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AccountRegisterBodyTest Class Doc Comment
 *
 * @category    Class
 * @description AccountRegisterBody
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AccountRegisterBodyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AccountRegisterBody"
     */
    public function testAccountRegisterBody()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "password"
     */
    public function testPropertyPassword()
    {
    }

    /**
     * Test attribute "salutation_id"
     */
    public function testPropertySalutationId()
    {
    }

    /**
     * Test attribute "first_name"
     */
    public function testPropertyFirstName()
    {
    }

    /**
     * Test attribute "last_name"
     */
    public function testPropertyLastName()
    {
    }

    /**
     * Test attribute "accepted_data_protection"
     */
    public function testPropertyAcceptedDataProtection()
    {
    }

    /**
     * Test attribute "storefront_url"
     */
    public function testPropertyStorefrontUrl()
    {
    }

    /**
     * Test attribute "billing_address"
     */
    public function testPropertyBillingAddress()
    {
    }

    /**
     * Test attribute "shipping_address"
     */
    public function testPropertyShippingAddress()
    {
    }

    /**
     * Test attribute "account_type"
     */
    public function testPropertyAccountType()
    {
    }

    /**
     * Test attribute "guest"
     */
    public function testPropertyGuest()
    {
    }

    /**
     * Test attribute "birthday_day"
     */
    public function testPropertyBirthdayDay()
    {
    }

    /**
     * Test attribute "birthday_month"
     */
    public function testPropertyBirthdayMonth()
    {
    }

    /**
     * Test attribute "birthday_year"
     */
    public function testPropertyBirthdayYear()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "affiliate_code"
     */
    public function testPropertyAffiliateCode()
    {
    }

    /**
     * Test attribute "campaign_code"
     */
    public function testPropertyCampaignCode()
    {
    }
}
