<?php
/**
 * CategoryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Store API
 *
 * This endpoint reference contains an overview of all endpoints comprising the Shopware Store API
 *
 * OpenAPI spec version: 6.4.8.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CategoryTest Class Doc Comment
 *
 * @category    Class
 * @description Added since version: 6.0.0.0
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CategoryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Category"
     */
    public function testCategory()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "version_id"
     */
    public function testPropertyVersionId()
    {
    }

    /**
     * Test attribute "parent_id"
     */
    public function testPropertyParentId()
    {
    }

    /**
     * Test attribute "parent_version_id"
     */
    public function testPropertyParentVersionId()
    {
    }

    /**
     * Test attribute "after_category_id"
     */
    public function testPropertyAfterCategoryId()
    {
    }

    /**
     * Test attribute "after_category_version_id"
     */
    public function testPropertyAfterCategoryVersionId()
    {
    }

    /**
     * Test attribute "media_id"
     */
    public function testPropertyMediaId()
    {
    }

    /**
     * Test attribute "display_nested_products"
     */
    public function testPropertyDisplayNestedProducts()
    {
    }

    /**
     * Test attribute "breadcrumb"
     */
    public function testPropertyBreadcrumb()
    {
    }

    /**
     * Test attribute "level"
     */
    public function testPropertyLevel()
    {
    }

    /**
     * Test attribute "path"
     */
    public function testPropertyPath()
    {
    }

    /**
     * Test attribute "child_count"
     */
    public function testPropertyChildCount()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "product_assignment_type"
     */
    public function testPropertyProductAssignmentType()
    {
    }

    /**
     * Test attribute "visible"
     */
    public function testPropertyVisible()
    {
    }

    /**
     * Test attribute "active"
     */
    public function testPropertyActive()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "custom_fields"
     */
    public function testPropertyCustomFields()
    {
    }

    /**
     * Test attribute "link_type"
     */
    public function testPropertyLinkType()
    {
    }

    /**
     * Test attribute "internal_link"
     */
    public function testPropertyInternalLink()
    {
    }

    /**
     * Test attribute "external_link"
     */
    public function testPropertyExternalLink()
    {
    }

    /**
     * Test attribute "link_new_tab"
     */
    public function testPropertyLinkNewTab()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "meta_title"
     */
    public function testPropertyMetaTitle()
    {
    }

    /**
     * Test attribute "meta_description"
     */
    public function testPropertyMetaDescription()
    {
    }

    /**
     * Test attribute "keywords"
     */
    public function testPropertyKeywords()
    {
    }

    /**
     * Test attribute "cms_page_id"
     */
    public function testPropertyCmsPageId()
    {
    }

    /**
     * Test attribute "cms_page_version_id"
     */
    public function testPropertyCmsPageVersionId()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }

    /**
     * Test attribute "translated"
     */
    public function testPropertyTranslated()
    {
    }

    /**
     * Test attribute "parent"
     */
    public function testPropertyParent()
    {
    }

    /**
     * Test attribute "children"
     */
    public function testPropertyChildren()
    {
    }

    /**
     * Test attribute "media"
     */
    public function testPropertyMedia()
    {
    }

    /**
     * Test attribute "cms_page"
     */
    public function testPropertyCmsPage()
    {
    }

    /**
     * Test attribute "seo_urls"
     */
    public function testPropertySeoUrls()
    {
    }
}
