<?php
/**
 * CategoryJsonApiRelationshipsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Store API
 *
 * This endpoint reference contains an overview of all endpoints comprising the Shopware Store API
 *
 * OpenAPI spec version: 6.4.8.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CategoryJsonApiRelationshipsTest Class Doc Comment
 *
 * @category    Class
 * @description CategoryJsonApiRelationships
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CategoryJsonApiRelationshipsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CategoryJsonApiRelationships"
     */
    public function testCategoryJsonApiRelationships()
    {
    }

    /**
     * Test attribute "parent"
     */
    public function testPropertyParent()
    {
    }

    /**
     * Test attribute "children"
     */
    public function testPropertyChildren()
    {
    }

    /**
     * Test attribute "media"
     */
    public function testPropertyMedia()
    {
    }

    /**
     * Test attribute "cms_page"
     */
    public function testPropertyCmsPage()
    {
    }

    /**
     * Test attribute "seo_urls"
     */
    public function testPropertySeoUrls()
    {
    }
}
