<?php
/**
 * ContextBodyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Store API
 *
 * This endpoint reference contains an overview of all endpoints comprising the Shopware Store API
 *
 * OpenAPI spec version: 6.4.8.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ContextBodyTest Class Doc Comment
 *
 * @category    Class
 * @description ContextBody
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ContextBodyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ContextBody"
     */
    public function testContextBody()
    {
    }

    /**
     * Test attribute "currency_id"
     */
    public function testPropertyCurrencyId()
    {
    }

    /**
     * Test attribute "language_id"
     */
    public function testPropertyLanguageId()
    {
    }

    /**
     * Test attribute "billing_address_id"
     */
    public function testPropertyBillingAddressId()
    {
    }

    /**
     * Test attribute "shipping_address_id"
     */
    public function testPropertyShippingAddressId()
    {
    }

    /**
     * Test attribute "payment_method_id"
     */
    public function testPropertyPaymentMethodId()
    {
    }

    /**
     * Test attribute "shipping_method_id"
     */
    public function testPropertyShippingMethodId()
    {
    }

    /**
     * Test attribute "country_id"
     */
    public function testPropertyCountryId()
    {
    }

    /**
     * Test attribute "country_state_id"
     */
    public function testPropertyCountryStateId()
    {
    }
}
