<?php
/**
 * SalesChannelContextSalesChannelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Store API
 *
 * This endpoint reference contains an overview of all endpoints comprising the Shopware Store API
 *
 * OpenAPI spec version: 6.4.8.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SalesChannelContextSalesChannelTest Class Doc Comment
 *
 * @category    Class
 * @description Information about the current sales channel
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SalesChannelContextSalesChannelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SalesChannelContextSalesChannel"
     */
    public function testSalesChannelContextSalesChannel()
    {
    }

    /**
     * Test attribute "type_id"
     */
    public function testPropertyTypeId()
    {
    }

    /**
     * Test attribute "language_id"
     */
    public function testPropertyLanguageId()
    {
    }

    /**
     * Test attribute "currency_id"
     */
    public function testPropertyCurrencyId()
    {
    }

    /**
     * Test attribute "payment_method_id"
     */
    public function testPropertyPaymentMethodId()
    {
    }

    /**
     * Test attribute "shipping_method_id"
     */
    public function testPropertyShippingMethodId()
    {
    }

    /**
     * Test attribute "country_id"
     */
    public function testPropertyCountryId()
    {
    }

    /**
     * Test attribute "navigation_category_id"
     */
    public function testPropertyNavigationCategoryId()
    {
    }

    /**
     * Test attribute "navigation_category_depth"
     */
    public function testPropertyNavigationCategoryDepth()
    {
    }

    /**
     * Test attribute "footer_category_id"
     */
    public function testPropertyFooterCategoryId()
    {
    }

    /**
     * Test attribute "service_category_id"
     */
    public function testPropertyServiceCategoryId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "short_name"
     */
    public function testPropertyShortName()
    {
    }

    /**
     * Test attribute "access_key"
     */
    public function testPropertyAccessKey()
    {
    }

    /**
     * Test attribute "active"
     */
    public function testPropertyActive()
    {
    }

    /**
     * Test attribute "maintenance"
     */
    public function testPropertyMaintenance()
    {
    }

    /**
     * Test attribute "maintenance_ip_whitelist"
     */
    public function testPropertyMaintenanceIpWhitelist()
    {
    }

    /**
     * Test attribute "mail_header_footer_id"
     */
    public function testPropertyMailHeaderFooterId()
    {
    }

    /**
     * Test attribute "customer_group_id"
     */
    public function testPropertyCustomerGroupId()
    {
    }

    /**
     * Test attribute "hreflang_active"
     */
    public function testPropertyHreflangActive()
    {
    }

    /**
     * Test attribute "hreflang_default_domain_id"
     */
    public function testPropertyHreflangDefaultDomainId()
    {
    }

    /**
     * Test attribute "analytics_id"
     */
    public function testPropertyAnalyticsId()
    {
    }
}
