<?php
/**
 * AddressApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Store API
 *
 * This endpoint reference contains an overview of all endpoints comprising the Shopware Store API
 *
 * OpenAPI spec version: 6.4.8.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * AddressApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AddressApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createCustomerAddress
     *
     * Create a new address for a customer.
     *
     */
    public function testCreateCustomerAddress()
    {
    }

    /**
     * Test case for defaultBillingAddress
     *
     * Change a customer's default billing address.
     *
     */
    public function testDefaultBillingAddress()
    {
    }

    /**
     * Test case for defaultShippingAddress
     *
     * Change a customer's default shipping address.
     *
     */
    public function testDefaultShippingAddress()
    {
    }

    /**
     * Test case for deleteCustomerAddress
     *
     * Delete an address of a customer.
     *
     */
    public function testDeleteCustomerAddress()
    {
    }

    /**
     * Test case for listAddress
     *
     * Fetch addresses of a customer.
     *
     */
    public function testListAddress()
    {
    }

    /**
     * Test case for updateCustomerAddress
     *
     * Modify an address of a customer.
     *
     */
    public function testUpdateCustomerAddress()
    {
    }
}
